name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      #- name: setup .net 5
      #  uses: actions/setup-dotnet@v1
      #  with:
      #        dotnet-version: '5.0.x'
      #- name: restore dependenices
      #  run: dotnet restore
      - name: build app
        run: dotnet build -c Release --no-restore
